- name: create ec2 and r53
  hosts: local
  connection: local
  vars:
   ami_id: ami-0220d79f3f480ecf5
   sg_id: sg-03b9d89518421df5f
   Zone_id: "Z03050851O7EFPQ87AMM1"
   domain_name: daws1.shop
  tasks:
    - name: create ec2 instance
      amazon.aws.ec2_instance:
        name: " {{ instance }}"
        instance_type: t3.micro
        security_group: "{{ sg_id }}"
        image_id: "{{ ami_id }}"
        tags: 
          NAme: "{{ instance }}"
        register: ec2_output

