- name: configure shipping server
  hosts: shipping
  become: yes
  tasks:

  - name: install required packages
    ansible.builtin.dnf:
      name:
        - maven
        - mysql
        - python3-PyMySQL
      state: present

  - name: create roboshop system user
    ansible.builtin.user:
      name: roboshop
      comment: RoboShop System user
      system: true
      shell: /sbin/nologin
      home: /app

  - name: remove old app directory
    ansible.builtin.file:
      path: /app
      state: absent

  - name: create app directory
    ansible.builtin.file:
      path: /app
      state: directory
      owner: roboshop
      group: roboshop

  - name: delete shipping zip if exists
    ansible.builtin.file:
      path: /tmp/shipping.zip
      state: absent

  - name: download shipping application
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip
      dest: /tmp/shipping.zip

  - name: extract shipping application
    ansible.builtin.unarchive:
      src: /tmp/shipping.zip
      dest: /app
      remote_src: yes
      owner: roboshop
      group: roboshop

  - name: build shipping application
    ansible.builtin.command: mvn clean package
    args:
      chdir: /app
    become_user: roboshop

  - name: move jar file
    ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
    args:
      chdir: /app
    become_user: roboshop

  - name: copy shipping systemd service
    ansible.builtin.copy:
      src: shipping.service
      dest: /etc/systemd/system/shipping.service

  - name: import shipping SQL files
    community.mysql.mysql_db:
      state: import
      name: cities
      login_host: mysql.daws1.shop
      login_user: root
      login_password: RoboShop@1
      target: "{{ item }}"
    loop:
      - /app/db/schema.sql
      - /app/db/app-user.sql
      - /app/db/master-data.sql

  - name: reload systemd and start shipping
    ansible.builtin.systemd:
      name: shipping
      enabled: true
      state: restarted
      daemon_reload: true